name: quant_finance
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - pytest
  - numpy
  - scipy
  - statsmodels
  - altair-all
  - vega_datasets
  - scikit-learn
  - tensorflow
  - matplotlib
  - tables
  - quandl
  - arch-py
